### ISSUE TITLE
Memory error with empty content in template

### ISSUE THREAD

**Issue by Dominionized** [knadh/listmonk#1191]
**Version:**
 - listmonk: [eg: v2.3.0]
 - OS: [e.g. Ubuntu 20.04.5 LTS]

**Description of the bug and steps to reproduce:**
When creating a campaign and not putting any content in it, listmonk panics because of a memory error.
To reproduce:
1. Create a new campaign (the default template is fine).
2. Delete all of the content in the content tab.
3. Click Preview or try to launch campaign or try to send test email

**Screenshots:**
Here is the error I get:
```
echo: http: panic serving 67.17.206.155:57888: runtime error: invalid memory address or nil pointer dereference
goroutine 230 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1802 +0xb9
panic({0xb07d60, 0x11c0780})
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
html/template.(*Template).lookupAndEscapeTemplate(0x0, {0xbadd96, 0x4})
	/opt/hostedtoolcache/go/1.17.13/x64/src/html/template/template.go:146 +0x50
html/template.(*Template).ExecuteTemplate(0xc000cf9520, {0xcdcae0, 0xc000166750}, {0xbadd96, 0xc00005efd0}, {0xb2a2a0, 0xc00077ed80})
	/opt/hostedtoolcache/go/1.17.13/x64/src/html/template/template.go:135 +0x38
github.com/knadh/listmonk/internal/manager.(*CampaignMessage).render(0xc00077ed80)
	/home/runner/work/listmonk/listmonk/internal/manager/manager.go:752 +0x13f
github.com/knadh/listmonk/internal/manager.(*Manager).NewCampaignMessage(_, _, {{0x0, {{0x0, 0x0, 0x0}, 0x0}, {{0x0, 0x0, 0x0}, ...}}, ...})
	/home/runner/work/listmonk/listmonk/internal/manager/manager.go:198 +0x215
main.handlePreviewCampaign({0xd073d0, 0xc000691ae0})
	/home/runner/work/listmonk/listmonk/cmd/campaigns.go:144 +0x6e5
github.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1({0xd073d0, 0xc000691ae0})
	/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/basic_auth.go:93 +0x4a5
github.com/labstack/echo/v4.(*Echo).add.func1({0xd073d0, 0xc000691ae0})
	/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x51
main.initHTTPServer.func1.1({0xd073d0, 0xc000691ae0})
	/home/runner/work/listmonk/listmonk/cmd/init.go:684 +0x5f
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000413680, {0xce9cd8, 0xc00077dce0}, 0xc000879c00)
	/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x3bc
net/http.serverHandler.ServeHTTP({0xc00013fdd0}, {0xce9cd8, 0xc00077dce0}, 0xc000879c00)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000691900, {0xced9a0, 0xc0001c0150})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:3034 +0x4e8
```

Thank you for the great project! 😄

**Comment by knadh** [comment]
Thanks for reporting. This is already fixed and will be available in the next release: https://github.com/knadh/listmonk/issues/1093

**Comment by ahorebhumio** [comment]
![image](https://github.com/user-attachments/assets/3a396d41-9404-4b87-a4f5-cdc2528d4bc2)
