### ISSUE TITLE
Preview new campaign cause panic and  restart

### ISSUE THREAD

**Issue by valenciaj** [knadh/listmonk#1223]
**Version:**
 - listmonk: v2.3.0
 - OS: Debian buster

When I create a new campaing, and click to preview cause panic and restart (systemd) listmonk process. But, when I do the same action over a existing or cloned campaign works properly.

Extracted log part:
```
Mar  2 00:01:40 mailings listmonk[10752]: echo: http: panic serving 127.0.0.1:49796: runtime error: invalid memory address or nil pointer dereference
Mar  2 00:01:40 mailings listmonk[10752]: goroutine 164 [running]:
Mar  2 00:01:40 mailings listmonk[10752]: net/http.(*conn).serve.func1()
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1802 +0xb9
Mar  2 00:01:40 mailings listmonk[10752]: panic({0xb07d60, 0x11c0780})
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
Mar  2 00:01:40 mailings listmonk[10752]: html/template.(*Template).lookupAndEscapeTemplate(0x0, {0xbadd96, 0x4})
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/html/template/template.go:146 +0x50
Mar  2 00:01:40 mailings listmonk[10752]: html/template.(*Template).ExecuteTemplate(0xc000c42000, {0xcdcae0, 0xc000ee2570}, {0xbadd96, 0xc000108fd0}, {0xb2a2a0, 0xc0009f4fc0
})
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/html/template/template.go:135 +0x38
Mar  2 00:01:40 mailings listmonk[10752]: github.com/knadh/listmonk/internal/manager.(*CampaignMessage).render(0xc0009f4fc0)
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/work/listmonk/listmonk/internal/manager/manager.go:752 +0x13f
Mar  2 00:01:40 mailings listmonk[10752]: github.com/knadh/listmonk/internal/manager.(*Manager).NewCampaignMessage(_, _, {{0x0, {{0x0, 0x0, 0x0}, 0x0}, {{0x0, 0x0, 0x0}, ...
}}, ...})
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/work/listmonk/listmonk/internal/manager/manager.go:198 +0x215
Mar  2 00:01:40 mailings listmonk[10752]: main.handlePreviewCampaign({0xd073d0, 0xc000bd6640})
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/work/listmonk/listmonk/cmd/campaigns.go:144 +0x6e5
Mar  2 00:01:40 mailings listmonk[10752]: github.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1({0xd073d0, 0xc000bd6640})
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/basic_auth.go:93 +0x4a5
Mar  2 00:01:40 mailings listmonk[10752]: github.com/labstack/echo/v4.(*Echo).add.func1({0xd073d0, 0xc000bd6640})
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x51
Mar  2 00:01:40 mailings listmonk[10752]: main.initHTTPServer.func1.1({0xd073d0, 0xc000bd6640})
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/work/listmonk/listmonk/cmd/init.go:684 +0x5f
Mar  2 00:01:40 mailings listmonk[10752]: github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000c166c0, {0xce9cd8, 0xc000886000}, 0xc000d82300)
Mar  2 00:01:40 mailings listmonk[10752]: #011/home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x3bc
Mar  2 00:01:40 mailings listmonk[10752]: net/http.serverHandler.ServeHTTP({0xc000ee2330}, {0xce9cd8, 0xc000886000}, 0xc000d82300)
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2879 +0x43b
Mar  2 00:01:40 mailings listmonk[10752]: net/http.(*conn).serve(0xc000bd6aa0, {0xced9a0, 0xc000c696e0})
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1930 +0xb08
Mar  2 00:01:40 mailings listmonk[10752]: created by net/http.(*Server).Serve
Mar  2 00:01:40 mailings listmonk[10752]: #011/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:3034 +0x4e8
```

**Comment by knadh** [comment]
Thanks for reporting. This is already fixed and will be available in the next release: https://github.com/knadh/listmonk/issues/1093

**Comment by valenciaj** [comment]
Great, have a nice day!
