### ISSUE TITLE
Error Request failed with status code 502

### ISSUE THREAD

**Issue by varundeva** [knadh/listmonk#128]
Why Showing Error
Request failed with status code 502 when i send campaign? i first tried to send test. it showing error
hosted on heroku
using amazon SES SMTP
added config var by seeing doc
`
2020-06-05T07:31:09.196340+00:00 heroku[router]: at=info method=POST path="/api/campaigns/3/test" host=bunews.herokuapp.com request_id=2fb16e4b-dc6f-454c-8df9-8a8c967d16c1 fwd="103.89.232.28" dyno=web.1 connect=0ms service=7ms status=502 bytes=295 protocol=https`

**Comment by knadh** [comment]
502 happens when a service is not running. Maybe listmonk crashed? You should look at the app logs.

**Comment by varundeva** [comment]
I've checked
See log is attached

Only that much log coming
I installed by using heroku deploy button
Manually added smtp variables

**Comment by varundeva** [comment]
```
2020-06-05T10:23:41.957509+00:00 heroku[router]: at=info method=GET path="/api/dashboard/stats" host=bunews.herokuapp.com request_id=a73bed3c-1e87-41ec-961d-2a8220da2914 fwd="103.89.232.31" dyno=web.1 connect=0ms service=2ms status=200 bytes=327 protocol=https
2020-06-05T10:23:42.922257+00:00 app[web.1]: measure#nginx.service=0.000 request_id=efd1327b-094c-4d15-964b-c89b04ce4d13
2020-06-05T10:23:42.923292+00:00 heroku[router]: at=info method=GET path="/frontend/manifest.json" host=bunews.herokuapp.com request_id=efd1327b-094c-4d15-964b-c89b04ce4d13 fwd="103.89.232.31" dyno=web.1 connect=0ms service=1ms status=401 bytes=759 protocol=https
2020-06-05T10:24:15.355621+00:00 heroku[router]: at=info method=POST path="/api/campaigns/3/test" host=bunews.herokuapp.com request_id=abe06465-c4cc-4b3a-b241-2675a96bb7bb fwd="103.89.232.31" dyno=web.1 connect=0ms service=6ms status=502 bytes=697 protocol=https
2020-06-05T10:24:15.352817+00:00 app[web.1]: echo: http: panic serving 127.0.0.1:41614: runtime error: index out of range [0] with length 0
2020-06-05T10:24:15.352829+00:00 app[web.1]: goroutine 92 [running]:
2020-06-05T10:24:15.352830+00:00 app[web.1]: net/http.(*conn).serve.func1(0xc00037ea00)
2020-06-05T10:24:15.352831+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1772 +0x139
2020-06-05T10:24:15.352831+00:00 app[web.1]: panic(0xa24d20, 0xc0003205a0)
2020-06-05T10:24:15.352831+00:00 app[web.1]: 	/usr/local/go/src/runtime/panic.go:973 +0x396
2020-06-05T10:24:15.352832+00:00 app[web.1]: github.com/knadh/listmonk/internal/messenger.(*Emailer).Push(0xc000326c30, 0xc000320360, 0x1d, 0xc000349190, 0x1, 0x1, 0xc000026570, 0x8, 0xc000079860, 0x192, ...)
2020-06-05T10:24:15.352833+00:00 app[web.1]: 	/home/kailash/code/go/my/knadh/listmonk/internal/messenger/emailer.go:100 +0x7a8
2020-06-05T10:24:15.352834+00:00 app[web.1]: main.sendTestMessage(0x3, 0x8c02c60, 0xed66bdd50, 0xc00012cf00, 0x1, 0x32e17b70, 0xed66be102, 0xc00012cf00, 0x1, 0xc000124540, ...)
2020-06-05T10:24:15.352834+00:00 app[web.1]: 	/home/kailash/code/go/my/knadh/listmonk/campaigns.go:565 +0x5d6
2020-06-05T10:24:15.352835+00:00 app[web.1]: main.handleTestCampaign(0xb5ea00, 0xc00017e070, 0xc00001e720, 0xa62cce)
2020-06-05T10:24:15.352835+00:00 app[web.1]: 	/home/kailash/code/go/my/knadh/listmonk/campaigns.go:541 +0xf6d
2020-06-05T10:24:15.352835+00:00 app[web.1]: github.com/labstack/echo.(*Echo).Add.func1(0xb5ea00, 0xc00017e070, 0x3, 0x9ba820)
2020-06-05T10:24:15.352836+00:00 app[web.1]: 	/home/kailash/code/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x8a
2020-06-05T10:24:15.352836+00:00 app[web.1]: main.initHTTPServer.func1.1(0xb5ea00, 0xc00017e070, 0x4, 0xc000124425)
2020-06-05T10:24:15.352837+00:00 app[web.1]: 	/home/kailash/code/go/my/knadh/listmonk/init.go:310 +0x88
2020-06-05T10:24:15.352837+00:00 app[web.1]: github.com/labstack/echo.(*Echo).ServeHTTP(0xc00034c000, 0xb4f6e0, 0xc000094540, 0xc00019c300)
2020-06-05T10:24:15.352837+00:00 app[web.1]: 	/home/kailash/code/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x222
2020-06-05T10:24:15.352838+00:00 app[web.1]: net/http.serverHandler.ServeHTTP(0xc00033c000, 0xb4f6e0, 0xc000094540, 0xc00019c300)
2020-06-05T10:24:15.352838+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:2807 +0xa3
2020-06-05T10:24:15.352839+00:00 app[web.1]: net/http.(*conn).serve(0xc00037ea00, 0xb51020, 0xc0001308c0)
2020-06-05T10:24:15.352839+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:1895 +0x86c
2020-06-05T10:24:15.352840+00:00 app[web.1]: created by net/http.(*Server).Serve
2020-06-05T10:24:15.352840+00:00 app[web.1]: 	/usr/local/go/src/net/http/server.go:2933 +0x35c
2020-06-05T10:24:15.352994+00:00 app[web.1]: 2020/06/05 10:24:15 [error] 33#0: *44 upstream prematurely closed connection while reading response header from upstream, client: 10.69.24.230, server: _, request: "POST /api/campaigns/3/test HTTP/1.1", upstream: "http://127.0.0.1:9000/api/campaigns/3/test", host: "bunews.herokuapp.com", referrer: "https://bunews.herokuapp.com/campaigns/3"
2020-06-05T10:24:15.355378+00:00 app[web.1]: measure#nginx.service=0.006 request_id=abe06465-c4cc-4b3a-b241-2675a96bb7bb
 Autoscroll with outputSave
Blogs
Careers
Documentation
Suppo
```

**Comment by mr-karan** [comment]
Ah, can you please show a list of all SMTP related env keys you added (with their actual values redacted?)

The stack trace seem to indicate [this](https://github.com/knadh/listmonk/blob/master/internal/messenger/emailer.go#L100) is the issue, but runtime config will be helpful to drill down.

**Comment by varundeva** [comment]
> Ah, can you please show a list of all SMTP related env keys you added (with their actual values redacted?)
> 
> The stack trace seem to indicate [this](https://github.com/knadh/listmonk/blob/master/internal/messenger/emailer.go#L100) is the issue, but runtime config will be helpful to drill down.
<a href="https://ibb.co/hM84dNJ"><img src="https://i.ibb.co/yRsZkCc/Fire-Shot-Capture-001-bunews-Settings-Heroku-dashboard-heroku-com.png" alt="Fire-Shot-Capture-001-bunews-Settings-Heroku-dashboard-heroku-com" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>image upload</a><br />

**Comment by knadh** [comment]
This happens when no SMTP configuration is found in the config. Ideally, it shouldn't crash (just added a check for that https://github.com/knadh/listmonk/commit/3048ab5afbbf46f4d81896085eb9f4aabaab3566)

I'm not familiar with the Heroku environment, but listmonk isn't receiving SMTP config.

**Comment by varundeva** [comment]
> This happens when no SMTP configuration is found in the config. Ideally, it shouldn't crash (just added a check for that [3048ab5](https://github.com/knadh/listmonk/commit/3048ab5afbbf46f4d81896085eb9f4aabaab3566))
> 
> I'm not familiar with the Heroku environment, but listmonk isn't receiving SMTP config.

Ok then need to add all variables there? i left additional smtp using details only.
Can you just say which are the mandatory env variables?

**Comment by mr-karan** [comment]
@knadh Can confirm, that is indeed the issue. `e.numServers` is `0` when none of the servers are read and the panic happens in [here](https://github.com/knadh/listmonk/blob/master/internal/messenger/emailer.go#L102) (the logs were a bit confusing, but I was able to replicate it correctly on my local config. `3048ab5` fixed it :+1:)

@varundeva Not that it should cause this, but I spotted a typo in your env config:

![image](https://user-images.githubusercontent.com/5689132/83873543-a0315a80-a751-11ea-9075-a710b0f02969.png)

Can you please confirm somehow, that the values you've shown here are indeed present inside Heroku's env?

Additionally, also run with the latest commit and you will see a helpful error message indicating that no SMTP servers are being read, which will also tell you that env variables are a problem with your setup

**Comment by varundeva** [comment]
> @knadh Can confirm, that is indeed the issue. `e.numServers` is `0` when none of the servers are read and the panic happens in [here](https://github.com/knadh/listmonk/blob/master/internal/messenger/emailer.go#L102) (the logs were a bit confusing, but I was able to replicate it correctly on my local config. `3048ab5` fixed it )
> 
> @varundeva Not that it should cause this, but I spotted a typo in your env config:
> 
> ![image](https://user-images.githubusercontent.com/5689132/83873543-a0315a80-a751-11ea-9075-a710b0f02969.png)
> 
> Can you please confirm somehow, that the values you've shown here are indeed present inside Heroku's env?
> 
> Additionally, also run with the latest commit and you will see a helpful error message indicating that no SMTP servers are being read, which will also tell you that env variables are a problem with your setup

Yes i tool screenshot from the Heroku Env

**Comment by varundeva** [comment]
I added all Config Variables by seeing example doc
Still Same Problem

**Comment by mr-karan** [comment]
I'm unable to replicate the issue. If you can print `env | grep LISTMONK` in Heroku and show logs, that would help.
