### ISSUE TITLE
Analytics Page Bug - Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by rpmcoding** [knadh/listmonk#1821]
**Version:**
 - listmonk: v3.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**

Go to analytics page, select a campaign and select a timeframe of around a year and click the blue search button.

Get this error in the console

`index-kDoPtQrv.js:41 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/campaigns/analytics?id=20".
    at ga (https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:17751)
    at IO (https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:17330)
    at Xe.confirmTransition (https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:20445)
    at Xe.transitionTo (https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:19787)
    at t.push (https://listmonk********.co/admin/static/index-kDoPtQrv.js:41:23117)
    at https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:27820
    at new Promise (<anonymous>)
    at ae.push (https://listmonk.********.co/admin/static/index-kDoPtQrv.js:41:27784)
    at o.onSubmit (https://listmonk.********.co/admin/static/CampaignAnalytics-v_l3a_aZ.js:1:2190)
    at submit (https://listmonk.********.co/admin/static/CampaignAnalytics-v_l3a_aZ.js:1:3901)`

##########

I also get this error in the console around a minute later.

`GET https://listmonk.*****.co/api/events?type=error 504 (Gateway Time-out)`

**Comment by rpmcoding** [comment]
Seems like a major bug...

**Comment by MaximilianKohler** [comment]
It works for me on v2.5.1.
![Screenshot 2024-04-12 075745](https://github.com/knadh/listmonk/assets/3606996/5731be80-3d02-409b-a198-f1d1f90331d1)

**Comment by rpmcoding** [comment]
Yep, was working fine in v2.  Seems to be a new bug in v3.

**Comment by knadh** [comment]
Able to replicate this issue on the 3.0.0 demo. https://demo.listmonk.app/admin/campaigns/analytics?id=2

This is confirmed as a bug. Don't know how I missed this, darn! Will add a frontend testcase for this also.

**Comment by lencell** [comment]
Hello,
is there any way to fix this, even as a temporary workaround ?  I can confirm this occur on freshly upgraded version 3.0.0

**Comment by JustAnotherEmployee** [comment]
Hi there,
Is there any update on this issue?
