### ISSUE TITLE
docker container quits

### ISSUE THREAD

**Issue by Joshfairhead** [knadh/listmonk#245]
Hello, I'm trying to get listmonk to run on my machine locally just to test it but something seems amiss. 

I start by pulling the container
`docker pull listmonk/listmonk:latest`

I try the following command
`docker-compose up -d demo-db demo-app`

And I get an error saying:
`Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?`

`Supported filenames: docker-compose.yml, docker-compose.yaml`

Assumably this is because the container is not running, so I enter docker and hit run. The container then spins up and immediately exits. Which I'm assuming is where the problem lies!

Any help getting up and running would be appreciate though, I believe I need to change the config file next but being new to docker I've no idea how to do that, though I've searched the net a few times. Honestly I don't even know where the image is kept to do that aside from "in docker"...

Thanks for your time!

**Comment by knadh** [comment]
Looks like you haven't copied the [docker-compose.yml](https://github.com/knadh/listmonk/blob/master/docker-compose.yml) to the directory where you're running the command.

**Comment by Joshfairhead** [comment]
Thanks, that makes sense - how might I do that though? I've had a rummage around the Docker documentation but if you have time it might make sense to add a section on how to do so in your docs so the uninformed (and new to development) like myself don't get stuck :)

**Comment by mr-karan** [comment]
@Joshfairhead You can check the docs [here](https://listmonk.app/docs/installation/#docker).

We're using `docker-compose` which is an abstraction for `docker` CLI. It makes things like spinning up dependent services easier (like Postgres in this case).

You just need to copy paste the contents of [docker-compose.yml](https://github.com/knadh/listmonk/blob/master/docker-compose.yml) and follow the instructions in the docs from there on.

**Comment by Joshfairhead** [comment]
Thanks @mr-karan,

Perhaps theres something wrong in my process so I started again. 

I start by going to `usr/mac/dev` where I keep my projects. Then I type the command `docker pull listmonk/listmonk:latest`. After this I paste the `docker-compose.yml` file into `usr/mac/dev` and type `docker-compose up -d demo-db demo-app`.

The result is different this time:
`ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 92, column 65`

I guess this is saying theres something wrong in the `docker-compose.yml` file? Any help appreciated :)

**Comment by mr-karan** [comment]
Don't really have to do: `docker pull listmonk/listmonk:latest.` (`docker-compose` will automatically pull it).

Looks like there's some spacing issue when you copied. Can you remove the old file, and simply:

```
$ wget -O docker-compose.yml https://raw.githubusercontent.com/knadh/listmonk/master/docker-compose.yml
$ docker-compose up demo-app demo-db
```

That should work ^

**Comment by Joshfairhead** [comment]
I'm afraid not; wget seems to grab the yaml file:
`--2021-01-11 19:24:59--  https://raw.githubusercontent.com/knadh/listmonk/master/docker-compose.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1098 (1.1K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml                           100%[============================================================================================>]   1.07K  --.-KB/s    in 0s

2021-01-11 19:25:00 (21.4 MB/s) - ‘docker-compose.yml’ saved [1098/1098]`

But `docker-compose up demo-app demo-db` doesn't and I get the following:
`Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[34119] Failed to execute script docker-compose`

**Comment by mr-karan** [comment]
It's unable to connect to `docker` socket. Looks like the Docker daemon isn't running. Since this is macOS please ensure Docker Desktop is running before you try `docker-compose` commands.

**Comment by Joshfairhead** [comment]
Thanks! That go me over the hurdles 👍
